In [24]:
# Work with HTML in memory
import pandas as pd
import requests
import glob
import matplotlib.pyplot as plt
% matplotlib inline
from bs4 import BeautifulSoup
import os

In [69]:
# Extract the title of the movie
df_list = []
folder = 'rt_html'
for movie_html in os.listdir(folder):
    with open(os.path.join(folder, movie_html)) as file:
        soup = BeautifulSoup(file, 'lxml')
        title = soup.find('title').contents[0][:-len(' - Rotten Tomatoes')]
        audience_score = soup.find('div', class_='audience-score meter').find('span').contents[0][:-1]
        num_audience_ratings = soup.find('div', class_='audience-info hidden-xs superPageFontColor')
        num_audience_ratings = num_audience_ratings.find_all('div')[1].contents[2].strip().replace(',','')
        df_list.append({'title':title,
                       'audience_score':int(audience_score),
                       'num_audience_ratings': int(num_audience_ratings)})
        df = pd.DataFrame(df_list, columns = ['title', 'audience_score', 'num_audience_ratings'])

In [71]:
df1.head(1)

,title,audience_score,num_audience_ratings
0,12 Angry Men (Twelve Angry Men) (1957),97,103672

In [86]:
# to be deleted
# Extract the title of the movie
df_list = []
folder = 'rt_html'
for movie_html in os.listdir(folder):
    with open(os.path.join(folder, movie_html)) as file:
        soup = BeautifulSoup(file, 'lxml')
        title = soup.find('title').contents[0][:-len(' - Rotten Tomatoes')]
        audience_score = soup.find('div', class_='audience-score meter').find('span').contents[0][:-1]
        num_audience_ratings = soup.find('div', class_='audience-info hidden-xs superPageFontColor')
        num_audience_ratings = num_audience_ratings.find_all('div')[1].contents[2].strip().replace(',','')
        df_list.append({'title':title,
                       'audience_score':int(audience_score),
                       'num_audience_ratings': int(num_audience_ratings)})
        df = pd.DataFrame(df_list, columns = ['title', 'audience_score', 'num_audience_ratings'])

In [87]:
# to be deleted
df = df.set_index('title')
df.head()

                                        audience_score  num_audience_ratings
title
12 Angry Men (Twelve Angry Men) (1957)              97                103672
The 39 Steps (1935)                                 86                 23647
The Adventures of Robin Hood (1938)                 89                 33584
All About Eve (1950)                                94                 44564
All Quiet on the Western Front (1930)               89                 17768

In [88]:
# to be deleted
df2 = pd.read_csv('bestofrt.tsv', sep = '\t')
df2 = df2.set_index('title')
df2.head()

                           ranking  critic_score  number_of_critic_ratings
title
The Wizard of Oz (1939)          1            99                       110
Citizen Kane (1941)              2           100                        75
The Third Man (1949)             3           100                        77
Get Out (2017)                   4            99                       282
Mad Max: Fury Road (2015)        5            97                       370

In [102]:
# to be deleted
df2.index = df2.index.str.strip()
df3 = pd.merge(df2, df1, left_index=True, right_index=False)
df3.head(3)

MergeError: Must pass right_on or right_index=True

In [62]:
df2 = pd.read_csv('bestofrt.tsv', sep = '\t')
df2

,ranking,critic_score,title,number_of_critic_ratings
0,1,99,The Wizard of Oz (1939),110
1,2,100,Citizen Kane (1941),75
2,3,100,The Third Man (1949),77
3,4,99,Get Out (2017),282
4,5,97,Mad Max: Fury Road (2015),370
5,6,100,The Cabinet of Dr. Caligari (Das Cabinet des D...,49
6,7,100,All About Eve (1950),64
7,8,98,Inside Out (2015),324
8,9,99,The Godfather (1972),85
9,10,99,Metropolis (1927),116
10,11,98,E.T. The Extra-Terrestrial (1982),114
11,12,100,Modern Times (1936),53
12,13,98,It Happened One Night (1934),52
13,14,100,Singin' in the Rain (1952),49
14,15,98,Boyhood (2014),283
15,16,97,Casablanca (1942),74
16,17,98,Moonlight (2016),292
17,18,97,Psycho (1960),86
18,19,100,Laura (1944),60
19,20,97,"Nosferatu, a Symphony of Horror (Nosferatu, ei...",62
20,21,98,Snow White and the Seven Dwarfs (1937),47
21,22,98,A Hard Day's Night (1964),104
22,23,97,La Grande illusion (Grand Illusion) (1938),63
23,24,100,North by Northwest (1959),65
24,25,99,The Battle of Algiers (La Battaglia di Algeri)...,83
25,26,93,Dunkirk (2017),337
26,27,100,The Maltese Falcon (1941),50
27,28,100,Repulsion (1965),60
28,29,96,12 Years a Slave (2013),316
29,30,96,Gravity (2013),315
...,...,...,...,...
70,71,100,Rebecca (1940),48
71,72,99,Rosemary's Baby (1968),69
72,73,99,Finding Nemo (2003),256
73,74,97,Brooklyn (2015),243
74,75,98,The Wrestler (2008),222
75,76,98,The 39 Steps (1935),44
76,77,99,L.A. Confidential (1997),108
77,78,94,Gone With the Wind (1939),83
78,79,97,"The Good, the Bad and the Ugly (1966)",68
79,80,93,Skyfall (2012),349
80,81,100,Open City (1946),41
81,82,100,Tokyo Story (Tôkyô monogatari) (1953),42
82,83,97,Hell or High Water (2016),237
83,84,100,Pinocchio (1940),45
84,85,95,The Jungle Book (2016),284
85,86,92,La La Land (2016),358
86,87,95,Star Trek (2009),336
87,88,96,High Noon (1952),50
88,89,98,Apocalypse Now (1979),80
89,90,98,On the Waterfront (1954),61
90,91,100,The Wages of Fear (1953),40
91,92,100,The Last Picture Show (1971),51
92,93,96,Harry Potter and the Deathly Hallows - Part 2 ...,314
93,94,100,The Grapes of Wrath (1940),43
94,95,98,Roman Holiday (1953),52
95,96,100,Man on Wire (2008),156
96,97,97,Jaws (1975),74
97,98,100,Toy Story (1995),78
98,99,97,"The Godfather, Part II (1974)",72
99,100,100,Battleship Potemkin (1925),45

In [68]:
df3 = pd.concat([df1, df2], axis=1, join='inner', ignore_index=False, join_axes = [df1.index])
df3

,title,audience_score,num_audience_ratings,ranking,critic_score,title,number_of_critic_ratings
0,12 Angry Men (Twelve Angry Men) (1957),97,103672,1,99,The Wizard of Oz (1939),110
1,The 39 Steps (1935),86,23647,2,100,Citizen Kane (1941),75
2,The Adventures of Robin Hood (1938),89,33584,3,100,The Third Man (1949),77
3,All About Eve (1950),94,44564,4,99,Get Out (2017),282
4,All Quiet on the Western Front (1930),89,17768,5,97,Mad Max: Fury Road (2015),370
5,Casablanca (1942),95,355952,6,100,The Cabinet of Dr. Caligari (Das Cabinet des D...,49
6,Frankenstein (1931),87,41140,7,100,All About Eve (1950),64
7,King Kong (1933),86,89669,8,98,Inside Out (2015),324
8,Laura (1944),91,10481,9,99,The Godfather (1972),85
9,M (1931),95,35778,10,99,Metropolis (1927),116
10,The Maltese Falcon (1941),91,57268,11,98,E.T. The Extra-Terrestrial (1982),114
11,Metropolis (1927),92,62018,12,100,Modern Times (1936),53
12,Rear Window (1954),95,149458,13,98,It Happened One Night (1934),52
13,Rebecca (1940),92,39026,14,100,Singin' in the Rain (1952),49
14,A Streetcar Named Desire (1951),90,54761,15,98,Boyhood (2014),283
15,Touch of Evil (1958),92,30867,16,97,Casablanca (1942),74
16,High Noon (1952),89,25065,17,98,Moonlight (2016),292
17,Snow White and the Seven Dwarfs (1937),78,469510,18,97,Psycho (1960),86
18,12 Years a Slave (2013),90,138789,19,100,Laura (1944),60
19,The 400 Blows (Les Quatre cents coups) (1959),94,38368,20,97,"Nosferatu, a Symphony of Horror (Nosferatu, ei...",62
20,Alien (1979),94,457186,21,98,Snow White and the Seven Dwarfs (1937),47
21,Apocalypse Now (1979),94,284606,22,98,A Hard Day's Night (1964),104
22,Argo (2012),90,207373,23,97,La Grande illusion (Grand Illusion) (1938),63
23,Army of Shadows (L'ArmÃ©e des ombres) (1969),94,7011,24,100,North by Northwest (1959),65
24,Arrival (2016),82,78740,25,99,The Battle of Algiers (La Battaglia di Algeri)...,83
25,Baby Driver (2017),89,48114,26,93,Dunkirk (2017),337
26,Battleship Potemkin (1925),85,18709,27,100,The Maltese Falcon (1941),50
27,A Hard Day's Night (1964),89,50067,28,100,Repulsion (1965),60
28,Bicycle Thieves (Ladri di biciclette) (1949),94,33723,29,96,12 Years a Slave (2013),316
29,Boyhood (2014),81,88478,30,96,Gravity (2013),315
...,...,...,...,...,...,...,...
70,Selma (2015),86,60533,71,100,Rebecca (1940),48
71,Seven Samurai (Shichinin no Samurai) (1956),97,90049,72,99,Rosemary's Baby (1968),69
72,Singin' in the Rain (1952),95,137643,73,99,Finding Nemo (2003),256
73,Skyfall (2012),86,372497,74,97,Brooklyn (2015),243
74,Spotlight (2015),93,68142,75,98,The Wrestler (2008),222
75,Star Trek (2009),91,746458,76,98,The 39 Steps (1935),44
76,Star Wars: Episode VII - The Force Awakens (2015),89,222789,77,99,L.A. Confidential (1997),108
77,Sunset Boulevard (1950),95,52783,78,94,Gone With the Wind (1939),83
78,Taxi Driver (1976),93,258405,79,97,"The Good, the Bad and the Ugly (1966)",68
79,The Babadook (2014),72,37024,80,93,Skyfall (2012),349
80,The Battle of Algiers (La Battaglia di Algeri)...,95,14267,81,100,Open City (1946),41
81,The Big Sick (2017),90,23391,82,100,Tokyo Story (Tôkyô monogatari) (1953),42
82,The Cabinet of Dr. Caligari (Das Cabinet des D...,89,27163,83,97,Hell or High Water (2016),237
83,The Conformist (1970),91,8529,84,100,Pinocchio (1940),45
84,The Dark Knight (2008),94,1827436,85,95,The Jungle Book (2016),284
85,"The Good, the Bad and the Ugly (1966)",97,238420,86,92,La La Land (2016),358
86,The Jungle Book (2016),86,92856,87,95,Star Trek (2009),336
87,The Third Man (1949),93,53081,88,96,High Noon (1952),50
88,The Wizard of Oz (1939),89,874425,89,98,Apocalypse Now (1979),80
89,The Wrestler (2008),88,139795,90,98,On the Waterfront (1954),61
90,Tokyo Story (TÃ´kyÃ´ monogatari) (1953),93,11325,91,100,The Wages of Fear (1953),40
91,Toy Story (1995),92,1107731,92,100,The Last Picture Show (1971),51
92,Toy Story 2 (1999),86,998186,93,96,Harry Potter and the Deathly Hallows - Part 2 ...,314
93,Toy Story 3 (2010),89,605098,94,100,The Grapes of Wrath (1940),43
94,The Treasure of the Sierra Madre (1948),93,25627,95,98,Roman Holiday (1953),52
95,Up (2009),90,1201878,96,100,Man on Wire (2008),156
96,Vertigo (1958),93,101454,97,97,Jaws (1975),74
97,The Wages of Fear (1953),95,8536,98,100,Toy Story (1995),78
98,Wonder Woman (2017),90,112955,99,97,"The Godfather, Part II (1974)",72
99,Zootopia (2016),92,98633,100,100,Battleship Potemkin (1925),45

In [57]:
df4 = pd.merge(df1, df2, on = 'title')
df4.head()

Empty DataFrame
Columns: [title, audience_score, num_audience_ratings, ranking, critic_score, number_of_critic_ratings]
Index: []

In [ ]:
plt.scatter(df.audience_score, df.critic_score)

In [ ]:
# Make directory if it doesn't already exist
folder_name = 'ebert_reviews'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

In [ ]:
ebert_review_urls = ['https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9900_1-the-wizard-of-oz-1939-film/1-the-wizard-of-oz-1939-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9901_2-citizen-kane/2-citizen-kane.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9901_3-the-third-man/3-the-third-man.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9902_4-get-out-film/4-get-out-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9902_5-mad-max-fury-road/5-mad-max-fury-road.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9902_6-the-cabinet-of-dr.-caligari/6-the-cabinet-of-dr.-caligari.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9903_7-all-about-eve/7-all-about-eve.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9903_8-inside-out-2015-film/8-inside-out-2015-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9903_9-the-godfather/9-the-godfather.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9904_10-metropolis-1927-film/10-metropolis-1927-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9904_11-e.t.-the-extra-terrestrial/11-e.t.-the-extra-terrestrial.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9904_12-modern-times-film/12-modern-times-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9904_14-singin-in-the-rain/14-singin-in-the-rain.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9905_15-boyhood-film/15-boyhood-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9905_16-casablanca-film/16-casablanca-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9905_17-moonlight-2016-film/17-moonlight-2016-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9906_18-psycho-1960-film/18-psycho-1960-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9906_19-laura-1944-film/19-laura-1944-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9906_20-nosferatu/20-nosferatu.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9907_21-snow-white-and-the-seven-dwarfs-1937-film/21-snow-white-and-the-seven-dwarfs-1937-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9907_22-a-hard-day27s-night-film/22-a-hard-day27s-night-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9907_23-la-grande-illusion/23-la-grande-illusion.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9908_25-the-battle-of-algiers/25-the-battle-of-algiers.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9908_26-dunkirk-2017-film/26-dunkirk-2017-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9908_27-the-maltese-falcon-1941-film/27-the-maltese-falcon-1941-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9909_29-12-years-a-slave-film/29-12-years-a-slave-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9909_30-gravity-2013-film/30-gravity-2013-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9909_31-sunset-boulevard-film/31-sunset-boulevard-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990a_32-king-kong-1933-film/32-king-kong-1933-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990a_33-spotlight-film/33-spotlight-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990a_34-the-adventures-of-robin-hood/34-the-adventures-of-robin-hood.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990b_35-rashomon/35-rashomon.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990b_36-rear-window/36-rear-window.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990b_37-selma-film/37-selma-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990c_38-taxi-driver/38-taxi-driver.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990c_39-toy-story-3/39-toy-story-3.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990c_40-argo-2012-film/40-argo-2012-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990d_41-toy-story-2/41-toy-story-2.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990d_42-the-big-sick/42-the-big-sick.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990d_43-bride-of-frankenstein/43-bride-of-frankenstein.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990d_44-zootopia/44-zootopia.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990e_45-m-1931-film/45-m-1931-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990e_46-wonder-woman-2017-film/46-wonder-woman-2017-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990e_48-alien-film/48-alien-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990f_49-bicycle-thieves/49-bicycle-thieves.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990f_50-seven-samurai/50-seven-samurai.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad990f_51-the-treasure-of-the-sierra-madre-film/51-the-treasure-of-the-sierra-madre-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9910_52-up-2009-film/52-up-2009-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9910_53-12-angry-men-1957-film/53-12-angry-men-1957-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9910_54-the-400-blows/54-the-400-blows.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9911_55-logan-film/55-logan-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9911_57-army-of-shadows/57-army-of-shadows.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9912_58-arrival-film/58-arrival-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9912_59-baby-driver/59-baby-driver.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9913_60-a-streetcar-named-desire-1951-film/60-a-streetcar-named-desire-1951-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9913_61-the-night-of-the-hunter-film/61-the-night-of-the-hunter-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9913_62-star-wars-the-force-awakens/62-star-wars-the-force-awakens.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9913_63-manchester-by-the-sea-film/63-manchester-by-the-sea-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9914_64-dr.-strangelove/64-dr.-strangelove.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9914_66-vertigo-film/66-vertigo-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9914_67-the-dark-knight-film/67-the-dark-knight-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9915_68-touch-of-evil/68-touch-of-evil.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9915_69-the-babadook/69-the-babadook.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9915_72-rosemary27s-baby-film/72-rosemary27s-baby-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9916_73-finding-nemo/73-finding-nemo.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9916_74-brooklyn-film/74-brooklyn-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9917_75-the-wrestler-2008-film/75-the-wrestler-2008-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9917_77-l.a.-confidential-film/77-l.a.-confidential-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9918_78-gone-with-the-wind-film/78-gone-with-the-wind-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9918_79-the-good-the-bad-and-the-ugly/79-the-good-the-bad-and-the-ugly.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9918_80-skyfall/80-skyfall.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9919_82-tokyo-story/82-tokyo-story.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9919_83-hell-or-high-water-film/83-hell-or-high-water-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9919_84-pinocchio-1940-film/84-pinocchio-1940-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9919_85-the-jungle-book-2016-film/85-the-jungle-book-2016-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991a_86-la-la-land-film/86-la-la-land-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991b_87-star-trek-film/87-star-trek-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991b_89-apocalypse-now/89-apocalypse-now.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991c_90-on-the-waterfront/90-on-the-waterfront.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991c_91-the-wages-of-fear/91-the-wages-of-fear.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991c_92-the-last-picture-show/92-the-last-picture-show.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991d_93-harry-potter-and-the-deathly-hallows-part-2/93-harry-potter-and-the-deathly-hallows-part-2.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991d_94-the-grapes-of-wrath-film/94-the-grapes-of-wrath-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991d_96-man-on-wire/96-man-on-wire.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991e_97-jaws-film/97-jaws-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991e_98-toy-story/98-toy-story.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991e_99-the-godfather-part-ii/99-the-godfather-part-ii.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad991e_100-battleship-potemkin/100-battleship-potemkin.txt']

In [ ]:
folder_name = 'ebert_reviews'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

for url in ebert_review_urls:
    response = requests.get(url)
    with open(os.path.join(folder_name, url.split('/')[-1]), mode = 'wb') as file:
        file.write(response.content)

In [ ]:
os.listdir(folder_name)

In [ ]:
# List of dictionaries to build file by file and later convert to a DataFrame
df_list = []
for ebert_review in glob.glob('ebert_reviews/*.txt'):
    with open(ebert_review, encoding='utf-8') as file:
        title = file.readline()[:-1]
        review_url = file.read()
        # Append to list of dictionaries
        df_list.append({'title': title,
                        'review_url': review_url,
                        'review_text': review_text})
df = pd.DataFrame(df_list, columns = ['title', 'review_url', 'review_text'])